spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: Welcome
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
