spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: Welcome
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dll-auto: none
      show-sql: true
